ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.example.cleancity.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/cleancity"
    user = "cleancity"
    password = "cleancity"
}

storage {
    path = "./uploads"
}
